Repository GSG-K3/Art-Gallery, pull requests merged in 2020-07, with the labels that each got.

#29 add eslint #24
  .eslintrc.js
  client/.eslintrc.js
  client/package.json
  package.json
Labels: waiting-review

#49 modefiy database build #25
  server/database/config/dbBuild.js
  server/database/config/dbBuild.sql
  server/database/config/dbConnection.js
Labels: back-end, waiting-review

#50 modify database ,dummy data ,create get art route
  server/app.js
  server/controllers/getArt.js
  server/controllers/index.js
  server/database/config/dbBuild.sql
  server/database/config/dummyData.sql
  server/database/queries/gitArt.js
Labels: back-end, waiting-review

#53 backend signup #52
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/signup.js
  server/database/queries/addUser.js
  server/database/queries/checkEmailQurey.js
  server/helper/signupValidation.js
  server/middlewares/checkEmail.js
Labels: back-end, waiting-review

#54 Login
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/logIn.js
  server/controllers/signup.js
  server/database/queries/getPassword.js
  server/middlewares/createToken.js
Labels: back-end, waiting-review

#55 adding art backend #56
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/postArt.js
  server/database/queries/addArtQuery.js
Labels: back-end, waiting-review

#57 create art slider #38
  client/package.json
  client/src/App.js
  client/src/Components/Common/RecentArtSlider/RecentArtSlider.js
  client/src/Components/Common/RecentArtSlider/sliderStyle.js
  client/src/Theme/MaterialTheme.js
  client/src/index.js
  server/controllers/index.js
  server/controllers/recentArt.js
  server/database/config/dbBuild.sql
  server/database/queries/recent.js
Labels: back-end, front-end, waiting-review

#61 Art-Card
  client/package.json
  client/src/App.js
  client/src/Components/Common/artCard/ArtCard.js
  client/src/Components/Common/homePage/Home.js
  client/src/Theme/MaterialTheme.js
  client/src/index.js
Labels: front-end, waiting-review

#59 Navbar
  client/public/index.html
  client/src/Components/Common/Navbar/Navbar.js
  client/src/Components/Common/Navbar/style.js
  client/src/Components/Common/index.js
Labels: front-end, waiting-review

#62 Header #36
  client/src/App.js
  client/src/Components/Common/Header/Header.js
  client/src/Components/Common/Header/Style.js
  client/src/index.js
Labels: front-end, waiting-review

#64 Categories slider
  client/package.json
  client/src/App.js
  client/src/Components/Common/categoriesSlider/CategoriesSlider.js
  client/src/Components/Common/categoriesSlider/Style.js
  server/controllers/logIn.js
Labels: front-end, in-progress, waiting-review

#66 Home page #40
  client/src/App.js
  client/src/Components/Common/ArtCard/ArtCard.js
  client/src/Components/Common/CategoriesSlider/CategoriesSlider.js
  client/src/Components/Common/CategoriesSlider/Style.js
  client/src/Components/Common/Header/Header.js
  client/src/Components/Common/Header/Style.js
  client/src/Components/Common/Navbar/Navbar.js
  client/src/Components/Common/RecentArtSlider/RecentArtSlider.js
  client/src/Components/Common/artCard/ArtCard.js
  client/src/Components/Common/categoriesSlider/CategoriesSlider.js
  client/src/Components/Common/homePage/Home.js
  client/src/Components/Layouts/HomePage/CategoriesHomeDiv.js
  client/src/Components/Layouts/HomePage/CustomizeHomeDiv.js
  client/src/Components/Layouts/HomePage/Gallery.js
  client/src/Components/Layouts/HomePage/Home.js
  client/src/Components/Layouts/HomePage/customize.png
  client/src/Components/Layouts/HomePage/style.js
  server/controllers/login.js
Labels: front-end, waiting-review

#71 Login & signUp Pages
  client/package.json
  client/src/App.js
  client/src/Components/Common/SecondHeder/SecondHeader.js
  client/src/Components/Layouts/Login/Login.js
  client/src/Components/Layouts/Login/PasswordForm.js
  client/src/Components/Layouts/helper/SignUpValidation.js
  client/src/Components/Layouts/signUp/SignUp.js
  client/src/Components/Layouts/signUp/SignUpForm.js
  client/src/Theme/FormsStyles.jsx
  server/controllers/checkAccount.js
  server/controllers/index.js
  server/controllers/logIn.js
  server/controllers/signup.js
  server/helper/signupValidation.js
Labels: Technical, waiting-review

#74 search page
  client/src/App.js
  client/src/Components/Common/ArtCard/ArtCard.js
  client/src/Components/Common/Header/Header.js
  client/src/Components/Common/Header/Style.js
  client/src/Components/Common/Navbar/Navbar.js
  client/src/Components/Common/Navbar/style.js
  client/src/Components/Common/RecentArtSlider/RecentArtSlider.js
  client/src/Components/Layouts/ArtInfo/ArtInfo.js
  client/src/Components/Layouts/HomePage/Gallery.js
  client/src/Components/Layouts/SearchPage/SearchPage.js
  client/src/Components/Layouts/SearchPage/style.js
  server/database/config/dbBuild.sql
  server/database/config/dummyData.sql
  server/database/queries/addArtQuery.js
Labels: Layout, front-end, waiting-approve, waiting-review

#78 shopping cart page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Common/Navbar/style.js
  client/src/Components/Common/SecondHeder/SecondHeader.js
  client/src/Components/Layouts/ArtInfo/ArtInfo.js
  client/src/Components/Layouts/ArtInfo/style.js
  client/src/Components/Layouts/HomePage/style.js
  client/src/Components/Layouts/Login/Login.js
  client/src/Components/Layouts/ShoppingCart/ShoppingCart.js
  client/src/Components/Layouts/ShoppingCart/style.js
  client/src/Components/Layouts/signUp/SignUp.js
  package-lock.json
  package.json
  server/controllers/addToCart.js
  server/controllers/clientCart.js
  server/controllers/deleteCartItem.js
  server/controllers/getUserId.js
  server/controllers/index.js
  server/database/config/dbBuild.sql
  server/database/config/dummyData.sql
  server/database/queries/addToCartQuery.js
  server/database/queries/clientCartQuery.js
  server/database/queries/deleteCartItemQuery.js
  server/database/queries/gitArt.js
Labels: Layout, back-end, front-end, waiting-review

#80 Customize
  client/package.json
  client/src/App.js
  client/src/Components/Layouts/Customize/UploadImage.js
  client/src/Components/Layouts/Customize/customize.js
  client/src/Components/Layouts/Customize/style.js
  client/src/Components/Layouts/Customize/useDraggable.js
  client/src/Components/Layouts/HomePage/CustomizeHomeDiv.js
  client/src/Components/Layouts/index.js
Labels: Technical, waiting-review

#83 add build
  package.json
Labels: DONE

#82 handling error front-end & back-end
  client/public/index.html
  client/src/App.js
  client/src/Components/Common/ArtCard/ArtCard.js
  client/src/Components/Common/RecentArtSlider/RecentArtSlider.js
  client/src/Components/Common/RecentArtSlider/sliderStyle.js
  client/src/Components/Errors/0-with-frame.jpg
  client/src/Components/Errors/5-frame.jpg
  client/src/Components/Errors/NotFoundError.js
  client/src/Components/Errors/ServerError.js
  client/src/Components/Errors/style.js
  client/src/Components/Layouts/ArtInfo/ArtInfo.js
  client/src/Components/Layouts/HomePage/Gallery.js
  client/src/Components/Layouts/HomePage/style.js
  client/src/Components/Layouts/SearchPage/SearchPage.js
  client/src/Components/Layouts/SearchPage/style.js
  client/src/Components/Layouts/ShoppingCart/ShoppingCart.js
  server/controllers/addToCart.js
  server/controllers/checkAccount.js
  server/controllers/clientCart.js
  server/controllers/deleteCartItem.js
  server/controllers/getArt.js
  server/controllers/getArtAndUser.js
  server/controllers/index.js
  server/controllers/postArt.js
  server/controllers/recentArt.js
  server/controllers/serverError.js
  server/database/config/dummyData.sql
  server/database/queries/gitArt.js
Labels: back-end, front-end, waiting-review

#75 Profile page
  client/src/App.js
  client/src/Components/Common/Header/Header.js
  client/src/Components/Common/Header/Style.js
  client/src/Components/Common/Navbar/Navbar.js
  client/src/Components/Layouts/ArtInfo/ArtInfo.js
  client/src/Components/Layouts/Login/Login.js
  client/src/Components/Layouts/ProfileArtist/addArt.png
  client/src/Components/Layouts/ProfileArtist/addButton.js
  client/src/Components/Layouts/ProfileArtist/allArt.js
  client/src/Components/Layouts/ProfileArtist/images.jpeg
  client/src/Components/Layouts/ProfileArtist/profile.js
  client/src/Components/Layouts/ProfileArtist/profileH.js
  client/src/Components/Layouts/ProfileArtist/profileHStyle.js
  client/src/Components/Layouts/ProfileArtist/style.js
  client/src/Components/Layouts/ProfileArtist/tab.js
  client/src/Components/Layouts/signUp/SignUpForm.js
  package.json
  server/app.js
  server/controllers/artsForArtist.js
  server/controllers/getArtist.js
  server/controllers/index.js
  server/database/queries/ArtworkForArtistQuery.js
  server/database/queries/getArtistQueries.js
Labels: in-progress

#88 add logout icon in header
  client/package-lock.json
  client/package.json
  client/src/Components/Common/Header/Header.js
  server/controllers/index.js
  server/controllers/logout.js
Labels: back-end, front-end, waiting-review

#70 Add art Form
  .gitignore
  client/.gitignore
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Common/ArtCard/ArtCard.js
  client/src/Components/Common/UplodeImage/uploadImage.js
  client/src/Components/Common/UplodeImage/uploadImageStyle.js
  client/src/Components/Layouts/ArtCard/ArtCard.js
  client/src/Components/Layouts/ArtInfo/ArtInfo.js
  client/src/Components/Layouts/ArtInfo/style.js
  client/src/Components/Layouts/ProfileArtist/addArt.png
  client/src/Components/Layouts/ProfileArtist/addButton.js
  client/src/Components/Layouts/ProfileArtist/profile.js
  client/src/Components/Layouts/ProfileArtist/style.js
  client/src/Components/Layouts/ProfileArtist/tab.js
  client/src/Components/Layouts/addArt/addArt.js
  client/src/Components/Layouts/addArt/addArtStyle.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/getArtist.js
  server/controllers/index.js
  server/controllers/uplodeImage.js
  server/database/config/dbBuild.sql
  server/database/queries/addArtQuery.js
Labels: DONE, T1D, back-end, front-end

#92 fixing
  .gitignore
  client/src/Components/Common/Header/Header.js
  client/src/Components/Common/Navbar/Navbar.js
  client/src/Components/Layouts/ArtInfo/ArtInfo.js
  client/src/Components/Layouts/Customize/UploadImage.js
  client/src/Components/Layouts/Customize/customize.js
  client/src/Components/Layouts/Login/Login.js
  client/src/Components/Layouts/ProfileArtist/addButton.js
  client/src/Components/Layouts/ProfileArtist/profile.js
  client/src/Components/Layouts/ProfileArtist/tab.js
  client/src/Components/Layouts/SearchPage/SearchPage.js
  client/src/Components/Layouts/ShoppingCart/ShoppingCart.js
  client/src/Components/Layouts/addArt/addArt.js
  client/src/Components/Layouts/addArt/addArtStyle.js
  client/src/Components/Layouts/helper/SignUpValidation.js
  server/controllers/postArt.js
  server/controllers/uplodeImage.js
  tmp/tmp-1-1595414032760
  tmp/tmp-1-1595418287165
  tmp/tmp-1-1595505375767
  tmp/tmp-10-1595419911997
  tmp/tmp-11-1595420001138
  tmp/tmp-12-1595420150192
  tmp/tmp-13-1595420262395
  tmp/tmp-14-1595420366039
  tmp/tmp-15-1595420461057
  tmp/tmp-16-1595420602840
  tmp/tmp-17-1595420728848
  tmp/tmp-18-1595420813431
  tmp/tmp-19-1595421683506
  tmp/tmp-2-1595418454959
  tmp/tmp-2-1595505523296
  tmp/tmp-20-1595421940147
  tmp/tmp-21-1595422319757
  tmp/tmp-22-1595422765391
  tmp/tmp-23-1595423432938
  tmp/tmp-24-1595423724904
  tmp/tmp-3-1595418583557
  tmp/tmp-3-1595505712913
  tmp/tmp-4-1595418710138
  tmp/tmp-4-1595505896634
  tmp/tmp-5-1595419024803
  tmp/tmp-5-1595506105833
  tmp/tmp-6-1595419140026
  tmp/tmp-6-1595506352700
  tmp/tmp-7-1595419544317
  tmp/tmp-7-1595506652255
  tmp/tmp-8-1595419778116
  tmp/tmp-9-1595419879072
Labels: bug, fix, in-progress
